language: php

php:
  - 8.0

os: linux

before_script:
  - composer install --no-ansi --no-interaction --no-progress --prefer-dist
  - cp .env.example .env
  - chmod -R 777 ./storage ./bootstrap/cache
  - php artisan key:generate

script:
  - vendor/bin/phpunit
