zend_extension=xdebug
[xdebug]
; Turn xdebug off by default, can be enabled through the environment variable XDEBUG_MODE
xdebug.mode=off
; host.docker.internal is IP of the the host machine as seen by docker (eg: 192.168.1.10)
xdebug.client_host=host.docker.internal
xdebug.client_port=9003
xdebug.idekey=PHPSTORM
xdebug.start_with_request=default
xdebug.log=/tmp/xdebug.log