name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest --no-dev --optimize-autoloader
      
    - name: Cache NPM packages
      id: npm-cache
      uses: actions/cache@v2
      with:
        path: node_modules
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-
      
    - name: Install NPM dependencies
      run: npm install

    - name: Run Laravel Mix
      run: npm run production
      
    - name: rsync deployment
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete --exclude '.env' 'node_modules/' 'storage/' 'bootstrap/cache/'
        path: /
        remote_path: /var/www/ping/
        remote_host: nicolus.fr
        remote_user: ubuntu
        remote_key: ${{ secrets.DEPLOY_KEY }}
      
    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
